### ISSUE TITLE
License ambiguity

### ISSUE THREAD

**Issue by slowpoke111** [saksham-joshi/SRON#1]
Their is no license on github, the code says MIT, and the installer says Propietray. Can you please clarify

**Comment by saksham-joshi** [comment]
Hello Ben Bell,

I am really sorry about that. I made this mistake unknowingly and I removed
the MIT license line from the code. I promise that such mistakes will not
happen again.

- Thank You

**Comment by saksham-joshi** [comment]
I am really sorry about that. I made this mistake unknowingly and I removed
the MIT license line from the code. I promise that such mistakes will not
happen again.

**Comment by slowpoke111** [comment]
Thank you for clayfying. keep up the good work

**Comment by saksham-joshi** [comment]
Hey there,

I have added the LICENSE file to the repository. I am really glad that someone is raising these issues to make SRON better.

Looking forward for more issues to be fixed in the future.

- Thank You
